/**
 * Forensics++ (ForensicsPP.com)
 * Local-first browser forensics workbench
 *
 * Copyright (c) 2026 DyNooob. All rights reserved.
 * Author: DyNooob
 * Website: https://www.forensicspp.com
 * Platform: DigiForensics.cn
 * Project: https://github.com/DyNooob/ForensicsPP
 *
 * Forensics++ is an open-source, browser-side toolkit for CTF/MISC,
 * lightweight forensic triage, encoding/decoding, metadata inspection,
 * hashes, archive parsing, and local analysis.
 *
 * Do not use this project for unauthorized access, intrusion,
 * privacy infringement, or unlawful activity.
 *
 * Released under the MIT License.
 * Full source code: https://github.com/DyNooob/ForensicsPP
 */

import CryptoJS from "crypto-js";
import { generateKeyPairSync } from "node:crypto";
import { describe, expect, it } from "vitest";
import { base64UrlEncode } from "../src/utils/base64";
import {
  extractJwtTokens,
  inspectJwtToken,
  jwtCryptoAlgorithm,
  signJwtAsymmetric,
  signJwtHS256,
  signJwtHmac,
  verifyJwtAsymmetricSignature
} from "../src/features/jwt/analyzer";

function bytesToB64Url(bytes: Uint8Array) {
  return btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

function spkiToPem(spki: Uint8Array) {
  return `-----BEGIN PUBLIC KEY-----\n${btoa(String.fromCharCode(...spki)).match(/.{1,64}/g)!.join("\n")}\n-----END PUBLIC KEY-----`;
}

function pemFromDer(der: Uint8Array, label: string) {
  return `-----BEGIN ${label}-----\n${btoa(String.fromCharCode(...der)).match(/.{1,64}/g)!.join("\n")}\n-----END ${label}-----`;
}

describe("JWT analyzer", () => {
  it("signJwtHS256 builds header.payload.signature with the correct HMAC", () => {
    const header = JSON.stringify({ alg: "HS256", typ: "JWT" });
    const payload = JSON.stringify({ sub: "1" });
    const secret = "s3cret";
    const token = signJwtHS256(header, payload, secret);
    const parts = token.split(".");
    expect(parts).toHaveLength(3);
    const data = `${base64UrlEncode(header)}.${base64UrlEncode(payload)}`;
    const expected = base64UrlEncode(CryptoJS.HmacSHA256(data, secret));
    expect(parts[2]).toBe(expected);
  });

  it("signJwtHmac supports HS384 and inspectJwtToken verifies it (regression for #HS384-verify-gap)", () => {
    const header = JSON.stringify({ alg: "HS384", typ: "JWT" });
    const payload = JSON.stringify({ sub: "u2" });
    const secret = "shared-secret";
    const token = signJwtHmac("HS384", header, payload, secret);
    const parts = token.split(".");
    expect(parts).toHaveLength(3);
    const data = `${base64UrlEncode(header)}.${base64UrlEncode(payload)}`;
    const expected = base64UrlEncode(CryptoJS.HmacSHA384(data, secret));
    expect(parts[2]).toBe(expected);

    const ok = inspectJwtToken(token, secret);
    expect(ok.findings.some((f) => /HMAC signature valid/.test(f.title))).toBe(true);
    const bad = inspectJwtToken(token, "nope");
    expect(bad.findings.some((f) => /HMAC signature invalid/.test(f.title))).toBe(true);
  });

  it("jwtCryptoAlgorithm maps RS/PS/ES and rejects non-asymmetric algs", () => {
    expect(jwtCryptoAlgorithm("RS256")).toEqual({ name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" });
    expect(jwtCryptoAlgorithm("ES512")).toEqual({ name: "ECDSA", namedCurve: "P-521", hash: "SHA-512" });
    expect(jwtCryptoAlgorithm("PS384")).toEqual({ name: "RSA-PSS", hash: "SHA-384", saltLength: 48 });
    expect(jwtCryptoAlgorithm("HS256")).toBeNull();
    expect(jwtCryptoAlgorithm("nope")).toBeNull();
  });

  it("extractJwtTokens keeps only tokens whose header and payload decode to JSON objects", () => {
    const valid = `${base64UrlEncode(JSON.stringify({ alg: "HS256", typ: "JWT" }))}.${base64UrlEncode(JSON.stringify({ sub: "1" }))}.sig`;
    const text = `see ${valid} and eyJh.yWV9 and eyJhIn0 and not.a and eyJ!bad and report.v2.final and aGVsbG8.d29ybGQ`;
    const tokens = extractJwtTokens(text);
    expect(tokens).toContain(valid);
    expect(tokens).not.toContain("eyJh.yWV9");
    expect(tokens).not.toContain("aGVsbG8.d29ybGQ");
  });

  it("extractJwtTokens accepts pretty-printed headers generated by the sign tab", () => {
    const token = "ewogICJhbGciOiAiSFMyNTYiLAogICJ0eXAiOiAiSldUIgp9.ewogIAp9.KpblrRK-urcxJ8QmStLHeNKd2OzYGqy9THGomi8uAGk";
    expect(extractJwtTokens(token)).toEqual([token]);
  });

  it("extractJwtTokens keeps '-' in base64url signatures and headers with non-ASCII", () => {
    const header = base64UrlEncode(JSON.stringify({ alg: "HS256", typ: "JWT", kid: "中文密钥-2026" }));
    const payload = base64UrlEncode(JSON.stringify({ sub: "u1" }));
    const sig = bytesToB64Url(new Uint8Array([0xfb, 0x8f])); // base64url "-48" — starts with '-'
    expect(sig).toContain("-");
    const full = `${header}.${payload}.${sig}`;
    expect(extractJwtTokens(full)).toEqual([full]);
  });

  it("inspectJwtToken validates the HMAC with the right secret and flags wrong secret / alg=none", () => {
    const header = JSON.stringify({ alg: "HS256", typ: "JWT" });
    const payload = JSON.stringify({ sub: "user" });
    const secret = "key";
    const token = signJwtHS256(header, payload, secret);

    const ok = inspectJwtToken(token, secret);
    expect(ok.findings.some((f) => /HMAC signature valid/.test(f.title))).toBe(true);

    const bad = inspectJwtToken(token, "wrongkey");
    expect(bad.findings.some((f) => /HMAC signature invalid/.test(f.title))).toBe(true);

    const noneToken = `${base64UrlEncode(JSON.stringify({ alg: "none" }))}.${base64UrlEncode(JSON.stringify({ sub: "x" }))}.`;
    const noneIns = inspectJwtToken(noneToken, secret);
    expect(noneIns.findings.some((f) => /Unsigned JWT/.test(f.title))).toBe(true);
  });

  it("verifyJwtAsymmetricSignature verifies a locally signed RS256 token and rejects a wrong key", async () => {
    const kp = await crypto.subtle.generateKey(
      { name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" },
      true,
      ["sign", "verify"]
    );
    const header = base64UrlEncode(JSON.stringify({ alg: "RS256", typ: "JWT" }));
    const payload = base64UrlEncode(JSON.stringify({ sub: "subject" }));
    const data = new TextEncoder().encode(`${header}.${payload}`);
    const sig = new Uint8Array(await crypto.subtle.sign({ name: "RSASSA-PKCS1-v1_5" }, kp.privateKey, data));
    const token = `${header}.${payload}.${bytesToB64Url(sig)}`;
    const pem = spkiToPem(new Uint8Array(await crypto.subtle.exportKey("spki", kp.publicKey)));

    const result = await verifyJwtAsymmetricSignature(token, pem);
    expect(result.status).toBe("valid");

    const wrong = await crypto.subtle.generateKey(
      { name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" },
      true,
      ["sign", "verify"]
    );
    const wrongPem = spkiToPem(new Uint8Array(await crypto.subtle.exportKey("spki", wrong.publicKey)));
    const badResult = await verifyJwtAsymmetricSignature(token, wrongPem);
    expect(badResult.status).toBe("invalid");
  });

  it("signJwtAsymmetric accepts a legacy PKCS#1 'RSA PRIVATE KEY' and verifies (regression for #pkcs1-sign)", async () => {
    const { privateKey: rsaPem, publicKey: pubPem } = generateKeyPairSync("rsa", {
      modulusLength: 2048,
      publicKeyEncoding: { type: "spki", format: "pem" },
      privateKeyEncoding: { type: "pkcs1", format: "pem" }
    });
    const header = JSON.stringify({ alg: "RS256", typ: "JWT" });
    const payload = JSON.stringify({ sub: "pkcs1-sign" });
    const token = await signJwtAsymmetric("RS256", header, payload, rsaPem);
    expect((await verifyJwtAsymmetricSignature(token, pubPem)).status).toBe("valid");
  });

  it("signJwtAsymmetric accepts a legacy SEC1 'EC PRIVATE KEY' and verifies (regression for #sec1-sign)", async () => {
    const { privateKey: ecPem, publicKey: pubPem } = generateKeyPairSync("ec", {
      namedCurve: "P-256",
      publicKeyEncoding: { type: "spki", format: "pem" },
      privateKeyEncoding: { type: "sec1", format: "pem" }
    });
    const header = JSON.stringify({ alg: "ES256", typ: "JWT" });
    const payload = JSON.stringify({ sub: "sec1-sign" });
    const token = await signJwtAsymmetric("ES256", header, payload, ecPem);
    expect((await verifyJwtAsymmetricSignature(token, pubPem)).status).toBe("valid");
  });
});
